### ISSUE TITLE
@pebula/nesbus conflicts when azure service is upgraded to v7

### ISSUE THREAD

**Issue by ihaalar** [shlomiassaf/pebula-node#13]
@pebula/nesbus conflicts when azure service is upgraded to v7. I'm unable to get the nestjs running when azure service bus is upgraded to latest version. On v1 the app works fine with @pebula/nesbus.

Can you please update @pebula/nesbus to work with latest version of azure service bus?

**Comment by mohammad-alnablse99** [comment]
yes the @azure/service-bus v7 is stable right now 
also, there are conflicts with @nestjs/common and @nestjs/core if you could upgrade peer dependencies that would be so much helpful

**Comment by shlomiassaf** [comment]
V7 is now supported, see https://github.com/pebula/node
