### ISSUE TITLE
Queue name from env

### ISSUE THREAD

**Issue by ghost** [shlomiassaf/pebula-node#8]
Hello,

I am unable to insert a string fetched from env into Queue name either through config service, process.env.QUEUE_NAME or through a util function returning queue string. Also `this` is not accessible either.

```
@Queue<MethodDecorator>({
    name: 'queue.name',
    // want to to do one of following. 
    //name: new ConfigService().get('AZURE_SERVICE_BUS_QUEUE'),
    // name: process.env.AZURE_SERVICE_BUS_QUEUE,
    // name: serviceBusQueueString(),

    receiveMode: ReceiveMode.peekLock,
    handlerOptions: {
      autoComplete: false,
    },
  })
  async myQueueEntity(@Ctx() context: SbContext): Promise<void> { //... 
}
```

**Comment by z3bra5hax** [comment]
process.env.AZURE_SERVICE_BUS_QUEUE will probably work if you properly use `dotenv`

**Comment by ghost** [comment]
unfortunately it's not picking value from dotenv
